# Generated by Django 6.0.4 on 2026-05-03 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewels', '0002_product_category_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Anti-Tarnish', 'Anti-Tarnish'), ('Pearl', 'Pearl'), ('Stainless steel', 'Stainless steel')], default='Pearl', max_length=20),
        ),
    ]
